apiVersion: apps/v1           # API version
kind: Deployment              # Type of kubernetes resource
metadata:
  name: whoami    # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: spring-boot
spec:
  replicas: 1                 # No. of replicas/pods to run in this deployment
  selector:
    matchLabels:              # The deployment applies to any pods mayching the specified labels
      app: spring-boot
  template:                   # Template for creating the pods in this deployment
    metadata:
      labels:                 # Labels that will be applied to each Pod in this deployment
        app: spring-boot
    spec:                     # Spec for the containers that will be run in the Pods
      containers:
      - name: whoami
        image: ghcr.io/eastmon94/whoami:latest
        # imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 8081 # The port that the container exposes
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:                  # Environment variables supplied to the Pod
        # - name: SPRING_DATASOURCE_USERNAME # Name of the environment variable
        #   value: usr
        # - name: SPRING_DATASOURCE_PASSWORD
        #   value: 1q2w3e4r
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://{{ .Release.Name }}-mysql.default.svc.cluster.local:3306/ssafy?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC