# This is a basic workflow to help you get started with Actions

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ (date +%s) }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: test
        run: echo "$version"
        env:
          version: ${{ env.VERSION }}
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag whoami:${version}
      #   env:
      #     version: ${{ env.VERSION }}

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.CR_PAT }}

      ## - name: Tag the Image
      #   run: docker image tag whoami:latest ghcr.io/eastmon94/whoami:$version

      # - name: push to Github Conatiner Registry
      #   run : docker image push ghcr.io/eastmon94/eastmon94/whoami:$version