# This is a basic workflow to help you get started with Actions

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/whoami:${{ github.sha }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: push to Github Conatiner Registry
        run : docker image push ghcr.io/${{ github.repository_owner }}/whoami:${{ github.sha }}

  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout another project
        uses: actions/checkout@master
        with: 
          repository: eastmon94/argocd
          # token: ${{ secrets.API_TOKEN_GITHUB }}
          path: .
        
      - name: config env
        run: sudo snap install yq

      - name: change file
        run : yq e '.spec.template.spec.containers[0].image = "ghcr.io/${{ github.repository_owner }}/whoami:${{ github.sha }}"' ./helmChart/templates/deployment.yaml

      - name: git config
        env:
          USER_NAME: ${{ github.event.pusher.name }}
          USER_EMAIL: ${{ github.event.pusher.email }}
        run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"
      
      - name: git add
        run: git add --all

      - name: git commit
        run: git commit -m "whoami update"
        
      - name: git push
        run: git push origin master