# This is a basic workflow to help you get started with Actions

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/whoami:${{ github.sha }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: push to Github Conatiner Registry
        run : docker image push ghcr.io/${{ github.repository_owner }}/whoami:${{ github.sha }}

  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout another project
        uses: actions/checkout@master
        with: 
          repository: eastmon94/argocd
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: .

        
      - name: config env
        run: snap install yq

      
      - name: commit
        run: |
        yq w ./helmChart/templates/deployment.yaml "spec.template.spec.containers[0].image" "ghcr.io/${{ github.repository_owner }}/whoami:${{ github.sha }}"
        git config user.name "Kim Donghyun"
        git config user.email "eastmon94@naver.com"
        git add .
        git commit -m "update"
        git push origin master